
export const villas = [
    {
      id: 1,
      name: "Villa Luna",
      location: "Greece",
      category: "Mountains",
      guests: 11,
      bedrooms: 6,
      bathrooms: 10,
      squareMeter: "400",
      rating: 4.7,
      image: "https://images.pexels.com/photos/3051551/pexels-photo-3051551.jpeg?auto=compress&cs=tinysrgb&w=600",
      dailyRent: "240",
    },
    {
      id: 2,
      name: "Villa Tosco",
      location: "Italy",
      category: "Mountains",
      guests: 8,
      bedrooms: 8,
      bathrooms: 12,
      squareMeter: "450",
      rating: 4.4,
      image: "https://images.pexels.com/photos/1506836/pexels-photo-1506836.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      dailyRent: "300",
    },
    {
      id: 3,
      name: "Aphrodite",
      location: "Greece",
      category: "Seaside",
      guests: 12,
      bedrooms: 6,
      bathrooms: 6,
      squareMeter: "500",
      rating: 4.9,
      image: "https://images.pexels.com/photos/14012685/pexels-photo-14012685.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      dailyRent: "200",
    },
    {
      id: 4,
      name: "Villa Makarska",
      location: "Italy",
      category: "Mountains",
      guests: 12,
      bedrooms: 15,
      bathrooms: 20,
      squareMeter: "750",
      rating: 5.0,
      image: "https://images.pexels.com/photos/3601420/pexels-photo-3601420.jpeg?auto=compress&cs=tinysrgb&w=600",
      dailyRent: "260",
    },
    {
      id: 5,
      name: "Villa Boxane",
      location: "Greece",
      category: "Mountains",
      guests: 4,
      bedrooms: 5,
      bathrooms: 6,
      squareMeter: "275",
      rating: 4.0,
      image: "https://images.pexels.com/photos/3205909/pexels-photo-3205909.jpeg?auto=compress&cs=tinysrgb&w=600",
      dailyRent: "200",
    },
    {
      id: 6,
      name: "Aphrodite",
      location: "Greece",
      category: "Seaside",
      guests: 12,
      bedrooms: 6,
      bathrooms: 6,
      squareMeter: "500",
      rating: 4.9,
      image: "https://images.pexels.com/photos/1449746/pexels-photo-1449746.jpeg?auto=compress&cs=tinysrgb&w=600",
      dailyRent: "320",
    },
    {
      id: 7,
      name: "Villa Sunset",
      location: "Italy",
      category: "Mountains",
      guests: 15,
      bedrooms: 8,
      bathrooms: 10,
      squareMeter: "1000",
      rating: 4.8,
      image: "https://images.pexels.com/photos/1488297/pexels-photo-1488297.png?auto=compress&cs=tinysrgb&w=600",
      dailyRent: "280",
    },
    {
      id: 8,
      name: "White Lady",
      location: "Italy",
      category: "Seaside",
      guests: 25,
      bedrooms: 25,
      bathrooms: 25,
      squareMeter: "1500",
      rating: 5.0,
      image: "https://images.pexels.com/photos/3320509/pexels-photo-3320509.jpeg?auto=compress&cs=tinysrgb&w=600",
      dailyRent: "400",
    },
    {
      id: 9,
      name: "Thebes",
      location: "Greece",
      category: "Seaside",
      guests: 5,
      bedrooms: 6,
      bathrooms: 6,
      squareMeter: "240",
      rating: 3.8,
      image: "https://images.pexels.com/photos/12720677/pexels-photo-12720677.jpeg?auto=compress&cs=tinysrgb&w=600",
      dailyRent: "180",
    },
  ];
  